services:
  app:
    build: .
    container_name: sem_app
    image: sem_app:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - se-methods
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    networks:
      - se-methods
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  se-methods:
    driver: bridge